### ISSUE TITLE
【功能请求】改善Bot在群组环境中的交互策略

### ISSUE THREAD

**Issue by KaRuichin** [Hellobaka/ChatGPTBot#1]
~~请求优化Bot群组环境的策略：~~
~~在群组环境时在会话加入角色 Prompt 提示词告诉AI这是在群组环境，而不是根据QQ号单独分配会话。首先希望可以将触发方式加入`@`和`引用Bot的消息`时，当用户@或者引用Bot的消息的时候在聊天内容前加入群员的名称和冒号（比如，在@的情况下为`群友A:你好`;当群员引用Bot的消息时在说明群员的昵称的基础上再加入群员引用的聊天内容）。~~

~~另外，希望可以在以上的角色** Prompt 提示词前加入优先级更高的基础提示词，这样可以让Bot管理员来自定义塑造Bot的角色。~~

感觉自个写的有点烂于是让AI优化了一下又改了改：

我建议对Bot在群组环境下的交互策略进行一些优化，以提升用户体验和互动质量。具体的建议如下：

1. **增强群组环境下的会话上下文识别**：
    - 当Bot在群组中被激活时（如通过`@Bot名称`或引用Bot的消息），应自动在回复内容前加上触发用户的昵称和冒号，以模拟更自然的对话流程。例如：
        - 当用户@Bot时，请求的回复格式为：“群友A：你好”。
        - 当用户引用Bot的消息时，除了包含用户昵称，还应附加引用的消息内容，以提供更丰富的上下文。

2. **引入角色Prompt提示词以增强会话上下文**：
    - 在当前的会话识别机制中，建议加入“角色Prompt提示词”，明确告知AI此次会话发生在群组环境中。这不仅有助于AI更好地理解会话背景，还可以根据群组的特性调整回复风格和内容。

3. **自定义角色Prompt提示词以塑造Bot角色**：
    - 为了让Bot管理员能够根据群组特性和需求，自定义塑造Bot的角色和个性，建议在角色Prompt提示词之前引入“基础提示词”。这些基础提示词应具有更高的优先级，使得管理员可以通过它们来定义Bot的基本行为模式和回复风格。

**Comment by Hellobaka** [comment]
你的意思是想让AI加入群组对话，这样你的token开销可小不了。有个预设功能啊，想整什么设定就整

**Comment by KaRuichin** [comment]
> 你的意思是想让AI加入群组对话，这样你的token开销可小不了。有个预设功能啊，想整什么设定就整

是的，开销不是问题可以通过群组白名单控制在指定的群组生效。
关于预设的话我希望在群组环境中优化一些像我刚刚修改的那部分说的：
> 1. **增强群组环境下的会话上下文识别**：
    - 当Bot在群组中被激活时（如通过`@Bot名称`或引用Bot的消息），应自动在回复内容前加上触发用户的昵称和冒号，以模拟更自然的对话流程。例如：
        - 当用户@Bot时，Bot回复格式为：“群友A：你好”。
        - 当用户引用Bot的消息时，除了包含用户昵称，还应附加引用的消息内容，以提供更丰富的上下文。

> 2. **引入角色Prompt提示词以增强会话上下文**：
    - 在当前的会话识别机制中，建议加入“角色Prompt提示词”，明确告知AI此次会话发生在群组环境中。这不仅有助于AI更好地理解会话背景，还可以根据群组的特性调整回复风格和内容。

**Comment by Hellobaka** [comment]
> - 当用户引用Bot的消息时，除了包含用户昵称，还应附加引用的消息内容，以提供更丰富的上下文。

引用上下文包括多少条，是包括其他人的消息还是只包含调用者的消息。
ps：我不认为这样会有什么有趣的回复，体验上感觉可能会不如群组对话时，群友可以自由插入对话而不是像现在这样只限制同一QQ

**Comment by KaRuichin** [comment]
> > * 当用户引用Bot的消息时，除了包含用户昵称，还应附加引用的消息内容，以提供更丰富的上下文。
> 
> 引用上下文包括多少条，是包括其他人的消息还是只包含调用者的消息。 ps：我不认为这样会有什么有趣的回复，体验上感觉可能会不如群组对话时，群友可以自由插入对话而不是像现在这样只限制同一QQ

1、关于引用Bot的上文消息只包括引用的那一条（比如如图只包括“哈哈哈哈哈哈哈”）。
![image](https://github.com/Hellobaka/ChatGPTBot/assets/69111766/a8c2458d-4ed3-431f-9afc-704a32a29723)

2、这样做是为了如果引用触发了对话的话Bot就知道自己在QQ群内被引用的那一段说了什么，而不是在API调用时的上一条对话。
（当然如果在QQ群内引用的那条消息就是AI会话当中AI的上一句话的话就可以忽略而只有说明发送者的名称）

**Comment by Hellobaka** [comment]
> 这样做是为了如果引用触发了对话的话Bot就知道自己在QQ群内被引用的那一段说了什么，而不是在API调用时的上一条对话。

按现在酷Q兼容框架来看，获取被回复的消息是不可能的，它会把引用消息变成一个单纯的At。尤其是被引用的消息不是同一个插件发送的时候，获取文本更是无从说起

**Comment by KaRuichin** [comment]
> > 这样做是为了如果引用触发了对话的话Bot就知道自己在QQ群内被引用的那一段说了什么，而不是在API调用时的上一条对话。
> 
> 按现在酷Q兼容框架来看，获取被回复的消息是不可能的，它会把引用消息变成一个单纯的At。尤其是被引用的消息不是同一个插件发送的时候，获取文本更是无从说起

这样啊，那本次功能请求剩下的没问题吧？

**Comment by Hellobaka** [comment]
> 加入“角色Prompt提示词”，明确告知AI此次会话发生在群组环境中
> 在角色Prompt提示词之前引入“基础提示词”。这些基础提示词应具有更高的优先级

是不是可以理解成一个自定义的初始Prompt

**Comment by KaRuichin** [comment]
> > 加入“角色Prompt提示词”，明确告知AI此次会话发生在群组环境中
> > 在角色Prompt提示词之前引入“基础提示词”。这些基础提示词应具有更高的优先级
> 
> 是不是可以理解成一个自定义的初始Prompt

是的在此基础上还有提示在群聊环境并且告知发送者的昵称，告知发送者的昵称的话私聊要也有就更好了 >_<

**Comment by Hellobaka** [comment]
没懂 给个例子看看

**Comment by KaRuichin** [comment]
> 没懂 给个例子看看

提示词：`你当前是在一个名为xxx的群聊内和群友们进行对话，我会以下面的格式帮你转述群友们说的内容：小明：你好！`
然后bot在群聊中被 @ 或者消息被引用时会使用 `群员昵称`：`消息内容`这样的格式去请求。

我也不知道这样是否有效，晚上有空我去测试出一个可行的出来。

或者可以在提示词模板中加入变量，比如群名称或者 @ or 引用消息的群友的昵称。并且群聊和私聊各可以设置一个默认的提示词模板，如果用户尝试加载其他模板的话，则把这个覆盖掉。

**Comment by Hellobaka** [comment]
> 被 @ 或者消息被引用时会使用 `群员昵称`：`消息内容`这样的格式去请求。

这么做的目的是什么

**Comment by KaRuichin** [comment]
> > 被 @ 或者消息被引用时会使用 `群员昵称`：`消息内容`这样的格式去请求。
> 
> 这么做的目的是什么

让AI知道是谁正在和他对话

**Comment by KaRuichin** [comment]
我又想了想或许是这样：
1、加入可以分别设置群聊和私聊的 **默认提示词** 功能。
2、加入一些 **变量** ，比如：对话者名称、群名称、消息内容（将在下一条使用）...等。
3、允许自定义向API发送的消息内容，比如我将群聊的自定义为 `<对话者昵称>：<消息内容>`。

**Comment by Hellobaka** [comment]
理解不了需求，调用者的名称对于会话来说没有意义啊，毕竟它只依赖上下文

**Comment by KaRuichin** [comment]
> 理解不了需求，调用者的名称对于会话来说没有意义啊，毕竟它只依赖上下文

感觉这样看起来Bot会更亲近智能，就像群友发的那样：
![image](https://github.com/Hellobaka/ChatGPTBot/assets/69111766/e0511c8a-3851-429f-ae53-ea7bc78eab68)
而不只是一个名为GPT的模型，使它更像Bot本人。

如果是像现在这样的话在群聊中就和私聊没区别了，比如另一位群友看着这边很有意思想要加入结果Bot就会转脸变成另一个人。
![image](https://github.com/Hellobaka/ChatGPTBot/assets/69111766/d1afdcfe-bf30-40cf-bf23-1d92245d6ba6)

**Comment by KaRuichin** [comment]
> 理解不了需求，调用者的名称对于会话来说没有意义啊，毕竟它只依赖上下文

我明白喜佬为什么不理解了，看来是我没有提到将现有的在**群聊中**上下文根据`QQ`绑定应改成根据`群ID`绑定。
> 
![image](https://github.com/Hellobaka/ChatGPTBot/assets/69111766/77305cc1-9fef-4fa5-9f04-2bc3274b0f2e)

**Comment by Hellobaka** [comment]
这下明白了
