### ISSUE TITLE
【功能请求】Bot 概率性主动参与聊天

### ISSUE THREAD

**Issue by KaRuichin** [Hellobaka/ChatGPTBot#2]
**简介**：希望增加一个功能，使 Bot 在群聊活跃时，有一定概率主动参与并回复最新的消息。

**具体描述**：当在群聊中，X 时间内消息数超过 Y 条时，以 Z% 的概率触发 Bot 主动回复最新一条消息（并附带之前 N 条的消息）。

**Comment by Hellobaka** [comment]
亲爱的 NierCaraLynn,

非常感谢你对我们项目的关注和支持，并提出了这个有趣的功能建议。我们团队一直在努力改进和扩展项目，因此你的反馈对我们来说非常宝贵。
我们会将你的需求记录在案，并在未来的规划中认真考虑。
感谢你的理解和耐心。如果你有其他的建议或想法，欢迎随时与我们分享。

祝好，
HelloBaka

**Comment by Hellobaka** [comment]
参照`1.8.0`版本

**Comment by KaRuichin** [comment]
亲爱的 Hellobaka，

非常感谢你在这么短的时间内就完成了我提出的功能请求！这个新功能对群聊体验的改善真是太棒了，期待它在实际使用中的表现。我非常欣赏你们团队的效率和对用户反馈的重视，真的让我感受到了你们对项目的用心。

如果未来我有其他想法，肯定会继续与你们交流。也希望这个项目越来越好！

再次感谢你的付出和努力。

祝好，
NierCaraLynn

**Comment by Hellobaka** [comment]
😡

**Comment by KaRuichin** [comment]
![b8f9cf643b08f08110807a3879c4057f](https://github.com/user-attachments/assets/898a8d63-3d29-4db0-877c-5851447ab1f5)
