### ISSUE TITLE
【BUG】某些图文消息格式下无法触发@回复

### ISSUE THREAD

**Issue by KaRuichin** [Hellobaka/ChatGPTBot#3]
![image](https://github.com/user-attachments/assets/a91b5842-973b-47a2-b0a0-a2cfba35cb98)

### 正常触发的消息格式
- 消息内容：`<@> text <图片>`  

![16e182522418f8bad052ff7771a735cb_720](https://github.com/user-attachments/assets/90869f64-7749-4a66-af51-6684132d771b)

### 无法触发的消息格式
以下消息格式会导致无法触发`@`回复：
1. `<图片> <@> text`
![320aa4e924e3ac1e1296c7322932d4b0](https://github.com/user-attachments/assets/244d7a0e-881e-47c9-bafe-baaa307c4072)

3. `text <@> <图片>`  
![3c83468632a34728033bffc42938bf8b_720](https://github.com/user-attachments/assets/6c99d56c-3bcc-4033-850c-9e4ff0a56eda)

**问题表现**：在以上两种情况下，日志显示插件未尝试处理消息。

**Comment by NierCaraLynn** [comment]
以下是一份简洁明了的 issue 模板：

---

### 标题：AI 插件带图片文字的 @ 无法触发回复

#### 描述问题  
在使用 AI 插件时，发现当消息中包含图片且带有文字 @ 时，AI 无法正确触发回复。这种情况下，即使文字部分符合触发规则，AI 仍未能识别并作出回应。

#### 复现步骤  
1. 在消息中插入一张图片，同时在图片外添加文字并 @ AI 插件。  
2. 确保文字部分符合触发条件（如关键词）。  
3. 发送消息，观察 AI 插件的反应。  

#### 预期行为  
AI 插件应正确识别消息中的文字 @，并触发相应的回复。  

#### 实际行为  
AI 插件未作出任何反应，似乎未能正确解析消息中的文字 @。  

#### 环境信息  
- AI 插件版本：  
- 使用平台（如微信、企业微信等）：  
- 设备类型（PC / 移动端）：  
- 操作系统版本：  

#### 附加信息  
如有必要，可附上相关截图或日志，帮助开发团队更好地理解问题。

---

这样撰写可以确保开发人员快速理解并重现问题。你可以根据实际情况调整内容。

**Comment by Hellobaka** [comment]
由于AT回复限制<@>消息在头部才能触发，所以后两种不触发回复是正确的

**Comment by KaRuichin** [comment]
> 由于AT回复限制<@>消息在头部才能触发，所以后两种不触发回复是正确的

是插件的限制吗？如果是的话可不可以加入一个新的配置项，只要消息内包含对Bot的<@>消息就触发回复

**Comment by KaRuichin** [comment]
阿里嘎多🥰
