### ISSUE TITLE
功能请求：新增概率触发回复条件

### ISSUE THREAD

**Issue by KaRuichin** [Hellobaka/ChatGPTBot#4]
（我把之前的那个想法也一块提过来了，麻烦喜佬了🥰🙏）

希望增加以下功能：

当检测到群友在一定时间内连续发送 N 条消息后，Bot 以某个概率触发回复（此概率通过一个独立的设置项来配置，不同于之前的随机参与聊天功能）。在触发回复时，将该用户在一定时间内连续发送的 N 条消息整合一同发送给 API 处理。

**Comment by Hellobaka** [comment]
https://github.com/Hellobaka/ChatGPTBot/releases/tag/1.11.0

**Comment by KaRuichin** [comment]
> https://github.com/Hellobaka/ChatGPTBot/releases/tag/1.10.0_

豪德
